In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical 

C:\Users\thewa\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (2.0.3)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(


In [4]:
df = pd.read_csv('diabetes.csv') 
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
X = df.drop('Outcome',axis = 1)

In [6]:
y = df['Outcome']

In [7]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
X = X.values

In [15]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [11]:
y = df['Outcome']



In [13]:
y = y.values

In [14]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(537, 8)
(231, 8)


In [30]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

count_classes = y_test.shape[1]
print(count_classes)

2


In [19]:
y_train

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [39]:
model = Sequential()
model.add(Dense(500, activation='relu', input_dim=8))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [40]:
model.fit(X_train, y_train, epochs=200)


Epoch 1/200
17/17 [==============================] - 1s 5ms/step - loss: 1.0532 - accuracy: 0.5940
Epoch 2/200
17/17 [==============================] - 0s 4ms/step - loss: 0.7160 - accuracy: 0.6071
Epoch 3/200
17/17 [==============================] - 0s 5ms/step - loss: 0.6541 - accuracy: 0.6462
Epoch 4/200
17/17 [==============================] - 0s 3ms/step - loss: 0.6028 - accuracy: 0.6760
Epoch 5/200
17/17 [==============================] - 0s 4ms/step - loss: 0.6201 - accuracy: 0.6667
Epoch 6/200
17/17 [==============================] - 0s 5ms/step - loss: 0.6036 - accuracy: 0.7039
Epoch 7/200
17/17 [==============================] - 0s 4ms/step - loss: 0.5864 - accuracy: 0.7058
Epoch 8/200
17/17 [==============================] - 0s 4ms/step - loss: 0.5959 - accuracy: 0.6983
Epoch 9/200
17/17 [==============================] - 0s 4ms/step - loss: 0.5783 - accuracy: 0.6872
Epoch 10/200
17/17 [==============================] - 0s 5ms/step - loss: 0.5826 - accuracy: 0.6816
Epoch 11/

17/17 [==============================] - 0s 5ms/step - loss: 0.4302 - accuracy: 0.7858
Epoch 82/200
17/17 [==============================] - 0s 7ms/step - loss: 0.4370 - accuracy: 0.7840
Epoch 83/200
17/17 [==============================] - 0s 12ms/step - loss: 0.4066 - accuracy: 0.8082
Epoch 84/200
17/17 [==============================] - 0s 8ms/step - loss: 0.4383 - accuracy: 0.7784
Epoch 85/200
17/17 [==============================] - 0s 7ms/step - loss: 0.4516 - accuracy: 0.7840
Epoch 86/200
17/17 [==============================] - 0s 9ms/step - loss: 0.4301 - accuracy: 0.7858
Epoch 87/200
17/17 [==============================] - 0s 6ms/step - loss: 0.4135 - accuracy: 0.7989
Epoch 88/200
17/17 [==============================] - 0s 4ms/step - loss: 0.4347 - accuracy: 0.7877
Epoch 89/200
17/17 [==============================] - 0s 6ms/step - loss: 0.4133 - accuracy: 0.8007
Epoch 90/200
17/17 [==============================] - 0s 8ms/step - loss: 0.4105 - accuracy: 0.8063
Epoch 91/200

17/17 [==============================] - 0s 4ms/step - loss: 0.2495 - accuracy: 0.8994
Epoch 160/200
17/17 [==============================] - 0s 4ms/step - loss: 0.2363 - accuracy: 0.8939
Epoch 161/200
17/17 [==============================] - 0s 4ms/step - loss: 0.2683 - accuracy: 0.8771
Epoch 162/200
17/17 [==============================] - 0s 3ms/step - loss: 0.2412 - accuracy: 0.8901
Epoch 163/200
17/17 [==============================] - 0s 3ms/step - loss: 0.2431 - accuracy: 0.8920
Epoch 164/200
17/17 [==============================] - 0s 4ms/step - loss: 0.2843 - accuracy: 0.8603
Epoch 165/200
17/17 [==============================] - 0s 3ms/step - loss: 0.2471 - accuracy: 0.8901
Epoch 166/200
17/17 [==============================] - 0s 4ms/step - loss: 0.2310 - accuracy: 0.8939
Epoch 167/200
17/17 [==============================] - 0s 3ms/step - loss: 0.2332 - accuracy: 0.8939
Epoch 168/200
17/17 [==============================] - 0s 3ms/step - loss: 0.2646 - accuracy: 0.8734
Epoc

In [49]:
from sklearn.metrics import f1_score
training_data_pred = model.predict(X_train) #class test
scores = model.evaluate(X_train, y_train, verbose=1) #x_train


17/17 [==============================] - 0s 3ms/step - loss: 0.2074 - accuracy: 0.9050


In [32]:
scores

[0.30734771490097046, 0.8603351712226868]

In [50]:
print(f"training accuracy is {scores[1]}")

training accuracy is 0.9050279259681702


In [51]:
print(f"training error is {1 - scores[1]}")

training error is 0.09497207403182983


In [52]:
pred_test= model.predict(X_test) #final_test


In [53]:
scores2 = model.evaluate(X_test, y_test, verbose=0)


In [54]:
print(f"test accuracy is {scores2[1]}")

test accuracy is 0.6709956526756287


In [55]:
print(f"test error is {1 - scores2[1]}")

test error is 0.32900434732437134
