In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler


C:\Users\thewa\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (2.0.3)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(


In [2]:
data = pd.read_csv("housing.csv")


In [3]:
data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [4]:
df_data = data.select_dtypes(include=[np.float,np.int])


In [5]:
df_data.info()  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64  
 4   OverallQual    1460 non-null   int64  
 5   OverallCond    1460 non-null   int64  
 6   YearBuilt      1460 non-null   int64  
 7   YearRemodAdd   1460 non-null   int64  
 8   MasVnrArea     1452 non-null   float64
 9   BsmtFinSF1     1460 non-null   int64  
 10  BsmtFinSF2     1460 non-null   int64  
 11  BsmtUnfSF      1460 non-null   int64  
 12  TotalBsmtSF    1460 non-null   int64  
 13  1stFlrSF       1460 non-null   int64  
 14  2ndFlrSF       1460 non-null   int64  
 15  LowQualFinSF   1460 non-null   int64  
 16  GrLivArea      1460 non-null   int64  
 17  BsmtFullBath   1460 non-null   int64  
 18  BsmtHalf

In [6]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [7]:
data = df_data.drop(['LotFrontage','MasVnrArea','GarageYrBlt','Id'],axis = 1)

In [8]:
data.isnull().sum()

MSSubClass       0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [9]:
data

MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0             60     8450            7            5       2003          2003   
1             20     9600            6            8       1976          1976   
2             60    11250            7            5       2001          2002   
3             70     9550            7            5       1915          1970   
4             60    14260            8            5       2000          2000   
...          ...      ...          ...          ...        ...           ...   
1455          60     7917            6            5       1999          2000   
1456          20    13175            6            6       1978          1988   
1457          70     9042            7            9       1941          2006   
1458          20     9717            5            6       1950          1996   
1459          20     9937            5            6       1965          1965   

      BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  ...  WoodDeckSF  \
0            706           0        150          856  ...           0   
1            978           0        284         1262  ...         298   
2            486           0        434          920  ...           0   
3            216           0        540          756  ...           0   
4            655           0        490         1145  ...         192   
...          ...         ...        ...          ...  ...         ...   
1455           0           0        953          953  ...           0   
1456         790         163        589         1542  ...         349   
1457         275           0        877         1152  ...           0   
1458          49        1029          0         1078  ...         366   
1459         830         290        136         1256  ...         736   

      OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  \
0              61              0          0            0         0        0   
1               0              0          0            0         0        0   
2              42              0          0            0         0        0   
3              35            272          0            0         0        0   
4              84              0          0            0         0        0   
...           ...            ...        ...          ...       ...      ...   
1455           40              0          0            0         0        0   
1456            0              0          0            0         0        0   
1457           60              0          0            0         0     2500   
1458            0            112          0            0         0        0   
1459           68              0          0            0         0        0   

      MoSold  YrSold  SalePrice  
0          2    2008     208500  
1          5    2007     181500  
2          9    2008     223500  
3          2    2006     140000  
4         12    2008     250000  
...      ...     ...        ...  
1455       8    2007     175000  
1456       2    2010     210000  
1457       5    2010     266500  
1458       4    2010     142125  
1459       6    2008     147500  

[1460 rows x 34 columns]

In [10]:
dataarray = data.values

In [11]:
dataarray

array([[    60,   8450,      7, ...,      2,   2008, 208500],
       [    20,   9600,      6, ...,      5,   2007, 181500],
       [    60,  11250,      7, ...,      9,   2008, 223500],
       ...,
       [    70,   9042,      7, ...,      5,   2010, 266500],
       [    20,   9717,      5, ...,      4,   2010, 142125],
       [    20,   9937,      5, ...,      6,   2008, 147500]], dtype=int64)

In [12]:
X = dataarray[:,0:33] #indepen var
Y = dataarray[:,-1] #dependent

In [13]:
Y

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

In [15]:
model = Sequential()
model.add(Dense(4, input_shape=(33,), activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))
model.compile(loss='mean_absolute_error', optimizer='adam')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 4)                 136       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 5         
Total params: 141
Trainable params: 141
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(X, Y, epochs=20, batch_size=32, validation_split = 0.2)


Epoch 1/20
37/37 [==============================] - 0s 4ms/step - loss: 94160.0391 - val_loss: 90171.5781
Epoch 2/20
37/37 [==============================] - 0s 2ms/step - loss: 85757.4219 - val_loss: 81317.4453
Epoch 3/20
37/37 [==============================] - 0s 3ms/step - loss: 77045.3672 - val_loss: 72470.3906
Epoch 4/20
37/37 [==============================] - 0s 3ms/step - loss: 68804.9531 - val_loss: 64410.9727
Epoch 5/20
37/37 [==============================] - 0s 3ms/step - loss: 61835.8281 - val_loss: 58010.5703
Epoch 6/20
37/37 [==============================] - 0s 3ms/step - loss: 56583.1797 - val_loss: 53679.7188
Epoch 7/20
37/37 [==============================] - 0s 3ms/step - loss: 53386.8164 - val_loss: 51101.4297
Epoch 8/20
37/37 [==============================] - 0s 4ms/step - loss: 51461.0156 - val_loss: 49527.7383
Epoch 9/20
37/37 [==============================] - 0s 6ms/step - loss: 50289.6992 - val_loss: 48656.6562
Epoch 10/20
37/37 [===========================

In [44]:
predictions = model.predict(X)


In [45]:
predictions

array([[81293.17 ],
       [85802.09 ],
       [93663.086],
       ...,
       [93629.66 ],
       [82443.47 ],
       [88041.5  ]], dtype=float32)

In [ ]:
from sklearn.metrics import r2_score
print(f"accuracy is {r2_score()}")